export const HOME_QUERIES_LIST: string[] = [
  "mobile wallpapers hd",
  "art mobile wallpapers",
  "aeshetic mobile wallpapers",
  "cool mobile wallpapers",
  "abstract mobile wallpapers",
  "nature mobile wallpapers",
  "minimalist mobile wallpapers",
  "dark mobile wallpapers",
  "space mobile wallpapers",
  "anime mobile wallpapers",
  "fantasy mobile wallpapers",
  "cityscape mobile wallpapers",
  "ocean mobile wallpapers",
  "mountain mobile wallpapers",
  "flower mobile wallpapers",
  "animal mobile wallpapers",
  "retro mobile wallpapers",
  "vintage mobile wallpapers",
  "pattern mobile wallpapers",
  "holiday mobile wallpapers",
  "sports mobile wallpapers",
  "gaming mobile wallpapers",
  "superhero mobile wallpapers",
  "quote mobile wallpapers",
  "motivational mobile wallpapers",
  "cyberpunk mobile wallpapers",
  "geometric mobile wallpapers",
  "technology mobile wallpapers",
  "food mobile wallpapers",
  "travel mobile wallpapers",
];

export const HOME_QUERY: string =
  HOME_QUERIES_LIST[Math.floor(Math.random() * HOME_QUERIES_LIST.length)];
